# Generated by Django 4.2.4 on 2023-11-03 08:07

import base.models
from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('school', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.spinschoolusers'),
        ),
        migrations.AddField(
            model_name='subject',
            name='state',
            field=models.ForeignKey(default=base.models.State.default_state, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classes'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grades'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='subject',
            field=models.ForeignKey(default=school.models.Subject.default_subject, on_delete=django.db.models.deletion.CASCADE, to='school.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.spinschoolusers'),
        ),
        migrations.AddField(
            model_name='jointstudentsubjectclass',
            name='Classes',
            field=models.ForeignKey(default=school.models.Classes.default_class, on_delete=django.db.models.deletion.CASCADE, to='school.classes'),
        ),
        migrations.AddField(
            model_name='jointstudentsubjectclass',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
        migrations.AddField(
            model_name='jointstudentsubjectclass',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject'),
        ),
        migrations.AddField(
            model_name='jointstudentsubjectclass',
            name='state',
            field=models.ForeignKey(default=base.models.State.default_state, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AddField(
            model_name='grades',
            name='state',
            field=models.ForeignKey(default=base.models.State.default_state, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AddField(
            model_name='classes',
            name='state',
            field=models.ForeignKey(default=base.models.State.default_state, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
    ]
