# Generated by Django 4.2.4 on 2023-10-31 08:47

from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_classes_options_alter_grades_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointstudentsubjectclass',
            name='Classes',
            field=models.ForeignKey(default=school.models.Classes.default_class, on_delete=django.db.models.deletion.CASCADE, to='school.classes'),
        ),
    ]
