# Generated by Django 4.2.4 on 2023-11-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_grades_score_studentscore_student_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
