# Generated by Django 4.2.4 on 2023-11-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_jointstudentsubjectclass_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reg_number',
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
